name: Build Windows Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create ExifTool directory
        run: |
          New-Item `
            -ItemType Directory `
            -Force `
            -Path "tools\exiftool" | Out-Null

      - name: Download ExifTool
        run: |
            curl.exe -L `
            "https://sourceforge.net/projects/exiftool/files/exiftool-13.59_64.zip/download" `
            -o tools\exiftool\exiftool.zip

      - name: Extract ExifTool
        run: |
          Expand-Archive `
            -Path tools\exiftool\exiftool.zip `
            -DestinationPath exiftool

      - name: Rename ExifTool
        run: |
          Copy-Item `
            "tools\exiftool\exiftool(-k).exe" `
            "tools\exiftool\exiftool.exe"    

      - name: Build executable
        run: |
          pyinstaller `
            --noconfirm `
            --clean `
            --windowed `
            --icon assets/unique-photo-transfer.ico `
            --add-data "assets;assets" `
            --add-binary "tools\exiftool\exiftool.exe;tools\exiftool" `
            --onefile `
            --name "Unique_Photo_Transfer" `
            main.py

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/Unique_Photo_Transfer.exe"
          generateReleaseNotes: true